export default function(){
  this.transition(
    this.hasClass('nextPage'),
    this.toValue(true),
    this.use('toRight'),
    this.reverse('toLeft')
  );
  this.transition(
    this.hasClass('slide'),
    this.toValue(true),
    this.use('toRight'),
    this.reverse('toLeft')
  );
  
  this.transition(
    this.fromRoute('overview'),
    this.toRoute('add-shift'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  
  this.transition(
    this.fromRoute('history'),
    this.toRoute('add-shift'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  
  this.transition(
    this.fromRoute('upcoming'),
    this.toRoute('add-shift'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  
  this.transition(
    this.fromRoute('overview'),
    this.toRoute('history'),
    this.use('fade'),
    this.reverse('fade')
  );
  
  this.transition(
    this.fromRoute('overview'),
    this.toRoute('upcoming'),
    this.use('fade'),
    this.reverse('fade')
  );
  
  this.transition(
    this.fromRoute('upcoming'),
    this.toRoute('history'),
    this.use('fade'),
    this.reverse('fade')
  );
  this.transition(
    this.fromRoute('overview'),
    this.toRoute('settings'),
    this.use('fade'),
    this.reverse('fade')
  );
  this.transition(
    this.fromRoute('history'),
    this.toRoute('settings'),
    this.use('fade'),
    this.reverse('fade')
  );
  this.transition(
    this.fromRoute('upcoming'),
    this.toRoute('settings'),
    this.use('fade'),
    this.reverse('fade')
  );
  this.transition(
    this.fromRoute('addShift'),
    this.toRoute('settings'),
    this.use('fade'),
    this.reverse('fade')
  );
};